@startuml
skinparam sequenceArrowThickness 2
skinparam roundcorner 5
skinparam maxmessagesize 180
skinparam sequenceParticipant bold
title  Create AllergyIntolerance
participant "FHIR Client" as A #CornflowerBlue
participant "MWS service " as B #CornflowerBlue
participant "MWS FHIR database" as C #CornflowerBlue

A -> B: POST[base]/AllergyIntolerance
B -> B: Validate
B -> C: create
C -[dashed]-> B:

B -[dashed]-> A:201 - Newly created MwsAllergyIntolerance
@enduml
