@startuml
skinparam sequenceArrowThickness 2
skinparam roundcorner 5
skinparam maxmessagesize 180
skinparam sequenceParticipant bold
title Get AllergyIntolerance by ID
actor "Integrating application user" as User #CornflowerBlue
participant "Integrating application" as A #CornflowerBlue
participant "MWS service" as B #CornflowerBlue
participant "MWS FHIR database" as C #CornflowerBlue
|||
User -> A: Enter AllergyIntolerance-id
activate A
|||
A -> B: GET [base]/AllergyIntolerance/[AllergyIntolerance-id]
activate B
|||
B -> B: Validate[]
|||
B -> C: Request
activate C
|||
C -[dashed]-> B:  
deactivate C
|||
B -[dashed]-> A :Return MwsAllergyIntolerance record 
deactivate B
|||
A -> User: Display AllergyIntolerance details
deactivate A
|||
@enduml
