openapi: '3.0.3'
info:
  version: '0.3.0'
  title: 'Prescription Counts API'
  description: API returning a count of the number of prescriptions dispensed for the given set of NHI numbers for the entitlement year, along with any Prescription Subsidy Card(s) if the entitlement exists
paths:
  /prescription-counts/{nhis}:
    parameters:
      - name: nhis
        description: List of one or more NHI numbers (separated by space %20)
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/NhiNumbers'
      - $ref: '#/components/parameters/X-correlation-ID'
      - $ref: '#/components/parameters/X-Request-Id'
      - $ref: '#/components/parameters/userid'
      - $ref: '#/components/parameters/request-context'
    get:
      summary: Get the count of dispensed prescriptions and any PSCs issued
     
      responses:
        200:
          description: Successful query
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrescriptionCounts'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        403:
          description: Not permitted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
                
      security:
        - hip-cognito:
          - "system/MedicationDispense.s"
            
      

components:

  parameters:
    X-correlation-ID:
      name: "X-correlation-ID"
      in: "header"
      required: false
      schema:
        type: "string"
    X-Request-Id:
      name: "X-Request-Id"
      in: "header"
      required: false
      schema:
        type: "string"
    x-api-key:
      name: "x-api-key"
      in: "header"
      required: true
      schema:
        type: "string"
    userid:
      name: "userid"
      in: "header"
      required: true
      schema:
        type: "string"
    request-context:
      name: "request-context"
      in: "header"
      required: true
      schema:
        type: "string"
  
  schemas: 
   
    NhiNumber:
        pattern: "^[A-HJ-NP-Z][A-HJ-NP-Z][A-HJ-NP-Z][0-9][0-9][0-9][0-9]|[A-HJ-NP-Z][A-HJ-NP-Z][A-HJ-NP-Z][0-9][0-9][A-HJ-NP-Z][A-HJ-NP-Z]$"
        type: "string"
        description: "unique 7-character identification number, assigned to a patien by the Patient Index."     
        
    NhiNumbers:
        pattern: "^[A-HJ-NP-Z][A-HJ-NP-Z][A-HJ-NP-Z][0-9][0-9][0-9][0-9]|[A-HJ-NP-Z][A-HJ-NP-Z][A-HJ-NP-Z][0-9][0-9][A-HJ-NP-Z][A-HJ-NP-Z]|%20$"
        type: "string"
        description: " List of NHI numbers seperated by space"
        example: "ZZZ0111%20ZZZ0112"   
      
    Prescription:
      type: object
      properties:
        
        whenPrepared:
          type: string
          format: date
          example: "2025-02-01"
        nhiNumber: 
          $ref: '#/components/schemas/NhiNumber'          
        medicationCode: 
           type: string
        medicationCodeSystem:
           type: string
        nzeps-pharmacy-approval-original:
            type: string
        nzeps-scriptno-local:
            type: string
      additionalProperties: false
      required:
        - "nhiNumber"
        - "whenPrepared"
        - "medicationCode"
        - "medicationCodeSystem"
        
        
            
    PrescriptionCounts:
      type: object
      properties:
        prescriptionCounts:
          type: array 
          items:
                $ref: '#/components/schemas/Prescription'
        totalPrescriptions:
          description: "grand total"
          type: integer
          format: int32
          example: 21 
       
   
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          description: Error code
          type: string
        message:
          description: A human readable error message
          type: string
          
  securitySchemes:
   
    hip-cognito:
      type: oauth2
      description: Client Credentials flow for system to system authentication
      flows:
        clientCredentials:
          tokenUrl: https://hpi-hip-uat.auth.ap-southeast-2.amazoncognito.com/oauth2/token
          scopes:
             system/MedicationDispense.s : Grant search access to MedicationDispense
      
